apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 3500
    protocol: TCP
  type: ClusterIP
  selector:
    role: api

# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   ports:
#     - port: 3001
#       targetPort: 3001
#   selector:
#     app: backend
#   type: ClusterIP #LoadBalancer #ClusterIP