apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 503561452156.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard2-nonprod-euw2:backend-latest
          env:
            - name: MONGO_URI
              value: "mongodb://root:asdasd@mongodb-service"
            - name: MONGO_DBNAME
              value: "backend"
            - name: APP_BACKEND_PORT
              value: "3001"
          ports:
            - containerPort: 3001