apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi