apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 503561452156.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard2-nonprod-euw2:frontend-latest
          env:
            - name: API_URL
              value:  "http://backend-srvice:3001/ #"http://wbapp.test.dv:3001/"
            - name: SOCKET_URL
              value: "http://backend-srvice:3001/"
            - name: FRONTEND_HOST
              value: "http://frontend-service:5000/"
            - name: NUXT_HOST
              value: "0.0.0.0"
            - name: NUXT_PORT
              value: "5000"
          ports:
            - containerPort: 5000
