apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "asdasd"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 503561452156.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard2-nonprod-euw2:backend-latest
          env:
            - name: MONGO_URI
              value: "mongodb://root:asdasd@mongodb-service"
            - name: MONGO_DBNAME
              value: "backend"
            - name: APP_BACKEND_PORT
              value: "3001"
          ports:
            - containerPort: 3001
          
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: backend
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 503561452156.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard2-nonprod-euw2:frontend-latest
          env:
            - name: API_URL
              value: "http://backend-service:3001/"
            - name: SOCKET_URL
              value: "http://backend-service:3001/"
            - name: FRONTEND_HOST
              value: "http://localhost:40000"
            - name: NUXT_HOST
              value: "0.0.0.0"
            - name: NUXT_PORT
              value: "5000"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  rules:
  - host: wbapp.test.dv
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-service
            port: 
              number: 5000
  ingressClassName: nginx
  
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wbapp-deployment
# spec:
#   replicas: 1
#   revisionHistoryLimit: 1
#   selector:
#     matchLabels:
#       app: wbapp
#   template:
#     metadata:
#       labels:
#         app: wbapp
#     spec:
#       containers:
#       - name: wbapp
#         image: 503561452156.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard2-nonprod-euw2:latest
#         ports:
#         - containerPort: 80